name: Auto commit

on:
  push:
    branches:
      - master
     
  schedule:
  - cron: "45 * * * 1-5" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3     
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "gerzsony@yahoo.com"
          git config --local user.name "gerzsony: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"
          git add -A
          
          arr[0]="Kyoko: 😂 auto commit"
          arr[1]="Kyoko: 😱 auto commit"
          arr[2]="Kyoko: 👿 auto commit"
          arr[3]="Kyoko: 💩 auto commit"
          arr[4]="Kyoko: 🙏 auto commit"
          arr[5]="Kyoko: 🙈 auto commit"
          arr[6]="Kyoko: 🐐 auto commit"
          arr[7]="Kyoko: 🤖 auto commit"
          arr[8]="Kyoko: 🟩 auto commit"
          arr[9]="Kyoko: 👻 auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]

          d=`date '+%Y-%m-%d %H:%M:%S'`
          
          git commit -m "${arr[$rand]} $d"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
